#!/usr/bin/env python3
import random
import argparse
from saveAndLoad import SaveAndLoad

parser = argparse.ArgumentParser(description="generates pseudo random words based on a file generated by in.py")

parser.add_argument('file_loc', help='the path to the .json file generated by in.py')
group2 = parser.add_mutually_exclusive_group()
group2.add_argument('-a', type=int, default=1, help='generates a set amount of pseudo random words')
group2.add_argument('-r', type=int, nargs=2, default=[1, 1],
                    help='a random amount of words between the bounds given ([a,b[)')

group = parser.add_mutually_exclusive_group()
group.add_argument('-m', type=int, default=0, help='set a minimum for the word length')
group.add_argument('-l', type=int, default=-1, help='set a precise length for the pseudo random word')

args = parser.parse_args()


file_in = args.file_loc
if args.a != 1:
    times = args.a
elif args.r[0] != 1 and args.r[1] != 0:
    times = random.randrange(args.r[0], args.r[1])
else:
    times = 1
min_word_length = args.m


previous_char = ' '
word = ''

my_obj = SaveAndLoad(file_in)

while times > 0:
    while True:
        previous_char = random.choices(my_obj.give_keys(previous_char), weights=my_obj.give_values(previous_char))[0]
        word += previous_char
        if previous_char == ' ':
            break
    if min_word_length <= len(word):
        print(word)
        times -= 1
    word = ''
